import { Verse } from './types';

export const verses: Verse[] = [
  {
    id: '1',
    reference: 'John 3:16',
    book: 'John',
    chapter: 3,
    verse: 16,
    text: 'For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.',
    imagePath: '/images/john-3-16.jpg',
    hint: 'Most famous verse about God\'s love',
    category: 'salvation',
  },
  {
    id: '2',
    reference: 'Psalm 23:1',
    book: 'Psalm',
    chapter: 23,
    verse: 1,
    text: 'The LORD is my shepherd; I shall not want.',
    imagePath: '/images/psalm-23-1.jpg',
    hint: 'About the Good Shepherd',
    category: 'comfort',
  },
  {
    id: '3',
    reference: 'Genesis 1:1',
    book: 'Genesis',
    chapter: 1,
    verse: 1,
    text: 'In the beginning God created the heaven and the earth.',
    imagePath: '/images/genesis-1-1.jpg',
    hint: 'The very first verse of the Bible',
    category: 'creation',
  },
  {
    id: '4',
    reference: 'Philippians 4:13',
    book: 'Philippians',
    chapter: 4,
    verse: 13,
    text: 'I can do all things through Christ which strengtheneth me.',
    imagePath: '/images/philippians-4-13.jpg',
    hint: 'About strength through Christ',
    category: 'strength',
  },
  {
    id: '5',
    reference: 'Proverbs 3:5-6',
    book: 'Proverbs',
    chapter: 3,
    verse: 5,
    text: 'Trust in the LORD with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths.',
    imagePath: '/images/proverbs-3-5-6.jpg',
    hint: 'About trusting God\'s guidance',
    category: 'wisdom',
  },
  {
    id: '6',
    reference: 'Romans 8:28',
    book: 'Romans',
    chapter: 8,
    verse: 28,
    text: 'And we know that all things work together for good to them that love God, to them who are the called according to his purpose.',
    imagePath: '/images/romans-8-28.jpg',
    hint: 'About God working all things for good',
    category: 'faith',
  },
];
